### ISSUE TITLE
Make "no method named" error more self explanatory

### ISSUE THREAD

**Issue by peterpeterparker** [dfinity/stable-structures#103]
I'm not sure it is possible but, rather like to open the issue just in case it is.

I have more than once faced following error when implementing `post_upgrade` methods in my canister:

```
error[E0599]: no method named `read` found for struct `VirtualMemory` in the current scope
  --> src/telemetry/src/lib.rs:43:12
   |
43 |     memory.read(4, &mut state_bytes);
   |            ^^^^ method not found in `VirtualMemory<Rc<RefCell<std::vec::Vec<u8>>>>`
```

Issue originates from code:

```
#[post_upgrade]
fn post_upgrade() {
    let memory: Memory = get_memory_upgrades();

    // Read the length of the state bytes.
    let mut state_len_bytes = [0; 4];
    memory.read(0, &mut state_len_bytes); // <---------------- here, .read unknown
```

Solution to this issue is adding following "unused" usage:

```
use ic_stable_structures::Memory as _;
```

So, if it there would be a way to make the compilation error more understable, that would be for sure appreciated I think.
Particularly for those who implement the stable structures for the very first time.

**Comment by ielashi** [comment]
In Rust, to use methods on a trait, you need to import that trait. There's not much we can change about that unfortunately.

**Comment by peterpeterparker** [comment]
I opened the question because that's the only single trait accross my all codebase that needs to be imported but, that is actually not used directly, that's why I thought it was worth asking. That and I'm also a Rust noob.

```
use ic_stable_structures::Memory as _; // ---> as _
```

Thanks for the feedback!

**Comment by ielashi** [comment]
By the way the `as _` is not necessary. The following should also work fine:

```
use ic_stable_structures::Memory as _; // ---> as _
```

`as _` can be useful in renaming if you want to reuse the name `Memory` somewhere else.
