### ISSUE TITLE
impl StableVec, StableHashMap.... for stable-structures

### ISSUE THREAD

**Issue by famouscat8** [dfinity/stable-structures#12]
impl StableVec, StableHashMap.... for stable-structures

**Comment by ielashi** [comment]
Hey @famouscat8, thanks for filing this. A `StableBTreeMap` can already simular a vec or a hashmap, so I don't think we need these, at least in the foreseeable future. If you have a specific use-case, feel free to open an issue to discuss it or post on the forums.
