### ISSUE TITLE
Why don’t you include the default `Storable` implementation for `bool`?

### ISSUE THREAD

**Issue by linnefromice** [dfinity/stable-structures#185]
There are cases where I want to use stable memory for things like flags that are represented by bools.
I think it would be possible to provide an implementation similar to the already existing one for u8.
Is it possible to provide this implementation?

The max_size is in bytes, so it may not be properly set, and the conversion to bool may not be optimal, but I have included an example of the code needed.

<details>
<summary>Example Code</summary>

```rust
impl Storable for bool {
    fn to_bytes(&self) -> Cow<[u8]> {
        let num: u8 = if *self { 1 } else { 0 };
        Cow::Owned(num.to_be_bytes().to_vec())
    }

    fn from_bytes(bytes: Cow<[u8]>) -> Self {
        let num = u8::from_be_bytes(bytes.as_ref().try_into().unwrap());
        match num {
            0 => false,
            1 => true,
            _ => panic!("Invalid bool encoding: expected 0 or 1, found {}", num)
        }
    }

    const BOUND: Bound = Bound::Bounded {
        max_size: 1,
        is_fixed_size: true,
    };
}
```

</details>

**Comment by ielashi** [comment]
Hi @linnefromice, thanks for filing this. Not implementing `bool` is an oversight and I don't see a reason to not implement it. How about you create a PR to add it? :)

**Comment by linnefromice** [comment]
Oh, I see. I'll give it a try. Thanks for the quick confirmation.

**Comment by ielashi** [comment]
Update: this is merged and is now awaiting a new release for this ticket to be closed.

**Comment by dragoljub-duric** [comment]
This is added in the new [0.6.3](https://github.com/dfinity/stable-structures/releases/tag/v0.6.3) Stable Structures release.
