### ISSUE TITLE
Question: What are risks in `unbound struct` including (variable-length) Vec field?

### ISSUE THREAD

**Issue by linnefromice** [dfinity/stable-structures#226]
It is understood that when storing Unbounded structures, the size of the stored data at the time is also stored and used when recovering to memory.

Q1: In the situation described above, where can problems arise when continuing to create/update the structure in question?

code image
```rust
#[derive(CandidType, Serialize, Deserialize, Clone, Debug)]
struct SnapshotIds {
    ids: Vec<SnapshotId>,
}

impl Storable for SnapshotIds {
    fn to_bytes(&self) -> std::borrow::Cow<[u8]> {
        std::borrow::Cow::Owned(Encode!(self).unwrap())
    }

    fn from_bytes(bytes: std::borrow::Cow<[u8]>) -> Self {
        Decode!(bytes.as_ref(), Self).unwrap()
    }
    const BOUND: ic_stable_structures::storable::Bound = Bound::Unbounded;
}
```

Q2. If Q1 can be used without problems, what problems could arise if this is used as a Value in a BTreeMap?

As a supplementary note, we are in the process of creating a flexible mechanism for storing as history data for user-defined data structures. we are trying to use BTreeMap from stable memory for storage of this history data. Also, as it is an arbitrary data structure for the user, we are always going to set Unbounded for the struct representing it. We wanted to know if there are any problems with this architecture.

**Comment by ielashi** [comment]
In theory what you mentioned is a valid use-case of a `BTreeMap`, and there shouldn't be any problems. The only caution here would be that, from a performance standpoint, this approach will be slow if users are storing a very large number of `ids` (e.g. tens of thousands), but if you don't anticipate that, then this architecture should be sufficient.

**Comment by linnefromice** [comment]
Thank you for your quick response.
If the number of `ids` becomes so large that the data exceeds the available heap memory (e.g. 4GB), then panic will occur during recovery, won't it? (Sorry if this question is outside the scope of this repository.)

**Comment by ielashi** [comment]
Yes, that is correct. I would say if you plan to store anything more than 10s of MiBs, then you should go with a different approach. For example, rather than having a map of `<User, Vec<SnapshotId>>` you should instead have `<(User, SnapshotId), ()>`. You can then use the `range` query on the btreemap to retrieve the snapshot IDs per user. That approach scales and is the approach we use in some of our production canisters.
