### ISSUE TITLE
bug: `MAX_SIZE` for `Blob<N>`

### ISSUE THREAD

**Issue by 0kenx** [dfinity/stable-structures#70]
Isn't the `MAX_SIZE` N+1?

https://github.com/dfinity/stable-structures/blob/265b9ab59c6d50a927a0ceea8eda417a474ce951/src/storable.rs#L116

**Comment by ielashi** [comment]
No. In the `Storable` trait, you do not need to store the size. When a struct is serialized using `Storable::to_bytes()`, the length of the vector already encodes that information, and structs like `BTreeMap` uses that information and encodes the size internally.
