### ISSUE TITLE
vec::InitError is now private

### ISSUE THREAD

**Issue by veeso** [dfinity/stable-structures#98]
Since 0.5.5 `vec::InitError` is private, which means the error returned by Vec::init cannot be accessed. Are there any reasons behind this or is it a mistake?

**Comment by ielashi** [comment]
@veeso Thanks for reporting this. I believe this is a mistake. We'll fix this and publish a new release shortly.

**Comment by ielashi** [comment]
@veeso We've now released 0.5.6, which should address this problem. Can you please try upgrading and let us know if everything is working the way you expect?

**Comment by veeso** [comment]
Thank you for the quick response! It's accessible now
